name:                gtk-gui
version:             0.1.0.0
github:              "stackbuilders/blog-code"
license:             BSD-3-Clause
author:              "Mark Karpov"
maintainer:          "jgalarza@stackbuilders.com"
copyright:           "2016 Mark Karpov"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/gtk-gui#readme>

dependencies:
- base >= 4.7 && < 5
- gtk3 >= 0.15.8 && < 0.15.9

build-tools:
- alex >= 3.4.0.1 && < 3.4.1
- happy >= 1.20.1.1 && < 1.20.2
- haskell-gi >= 0.26.8 && < 0.26.9
- gtk2hs-buildtools >= 0.13.10 && < 0.13.11

library:
  source-dirs: src

executables:
  gtk-gui-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - gtk-gui
